version: 0.2
      
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm ci
  build:
    commands:
      - npm run generate-s3
      - chmod +x './deployment/deploy-to-s3.sh' && './deployment/deploy-to-s3.sh'
