version: 0.2
      
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install hexo -g
      - npm install
  build:
    commands:
      - hexo generate --config _config.yml,_config.prod.yml
      - chmod +x './deployment/deploy-to-s3.sh' && './deployment/deploy-to-s3.sh'
